### ISSUE TITLE
npm and GitHub paths don't match

### ISSUE THREAD

**Issue by skue** [ProseMirror/prosemirror-test-builder#1]
In GitHub this repo is called `test-builder`, but in npm it's referenced as `prosemirror-test-builder`:

```
yarn info v0.21.3
{ name: 'prosemirror-test-builder',
  description: 'Helpers for programatically building ProseMirror test documents',
  'dist-tags': { latest: '0.19.0' },
  versions: [ '0.19.0' ],
  maintainers: 
   [ { name: 'marijn',
       email: 'marijnh@gmail.com' } ],
  time: 
   { modified: '2017-03-21T15:07:30.430Z',
     created: '2017-03-21T15:07:30.430Z',
     '0.19.0': '2017-03-21T15:07:30.430Z' },
  homepage: 'https://github.com/prosemirror/prosemirror-test-builder#readme',
  repository: 
   { type: 'git',
     url: 'git://github.com/prosemirror/prosemirror-test-builder.git' },
  bugs: { url: 'https://github.com/prosemirror/prosemirror-test-builder/issues' },
  license: 'MIT',
  readmeFilename: 'README.md',
  version: '0.19.0',
  main: 'dist/index.js',
  dependencies: 
   { 'prosemirror-model': '~0.19.0',
     'prosemirror-schema-basic': '~0.19.0',
     'prosemirror-schema-table': '~0.19.0' },
  devDependencies: 
   { buble: '^0.15.1',
     mocha: '^3.0.2',
     ist: '^1.0.0',
     rimraf: '^2.5.4' },
  scripts: 
   { test: 'mocha test/test-*.js',
     build: 'rimraf dist && buble -i src -o dist',
     prepublish: 'npm run build' },
  gitHead: '566590b9db36332c4d19131d550f3aff04d6ce97',
  dist: 
   { shasum: 'ad6ade7b3ef06fa9aede9f958c25b962bd6b83e7',
     tarball: 'https://registry.npmjs.org/prosemirror-test-builder/-/prosemirror-test-builder-0.19.0.tgz' },
  directories: {} }
✨  Done in 0.38s.
```

Believe this is causing the main prosemirror build process to break:

```
$ git clone https://github.com/ProseMirror/prosemirror.git prosemirror
...
$ cd prosemirror
$ yarn install
yarn install v0.21.3
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ bin/pm clone
Cloning into 'model'...
Cloning into 'transform'...
Cloning into 'state'...
Cloning into 'view'...
Cloning into 'keymap'...
Cloning into 'inputrules'...
Cloning into 'history'...
Cloning into 'collab'...
Cloning into 'commands'...
Cloning into 'schema-basic'...
Cloning into 'schema-list'...
Cloning into 'schema-table'...
Cloning into 'menu'...
Cloning into 'example-setup'...
Cloning into 'markdown'...
Cloning into 'dropcursor'...
Username for 'https://github.com': 
Password for 'https://github.com': 
Cloning into 'test-builder'...
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/prosemirror/prosemirror-test-builder.git/'
child_process.js:506
    throw err;
    ^

Error: Command failed: git clone https://github.com/prosemirror/prosemirror-test-builder.git test-builder
Cloning into 'test-builder'...
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/prosemirror/prosemirror-test-builder.git/'

    at checkExecSyncError (child_process.js:483:13)
    at Object.execFileSync (child_process.js:503:13)
    at run (/Users/username/Development/Repos/prosemirror-test/bin/pm.js:61:16)
    at modsAndWebsite.forEach.repo (/Users/username/Development/Repos/prosemirror-test/bin/pm.js:119:5)
    at Array.forEach (native)
    at clone (/Users/username/Development/Repos/prosemirror-test/bin/pm.js:116:18)
    at start (/Users/username/Development/Repos/prosemirror-test/bin/pm.js:31:32)
    at Object.<anonymous> (/Users/username/Development/Repos/prosemirror-test/bin/pm.js:261:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by marijnh** [comment]
Oh, that indeed won't work. I've renamed the repository to match the name that the script exects it to have
