### ISSUE TITLE
problem installing

### ISSUE THREAD

**Issue by palices** [ProseMirror/prosemirror-test-builder#4]
Problem installing prosemirror on linux mint at this point

```
Running yarn install
child_process.js:624
    throw err;
    ^

Error: spawnSync yarn ENOENT
    at Object.spawnSync (internal/child_process.js:981:20)
    at spawnSync (child_process.js:588:24)
    at Object.execFileSync (child_process.js:616:13)
    at run (/home/tony/prosemirror/bin/pm.js:80:16)
    at install (/home/tony/prosemirror/bin/pm.js:141:3)
    at start (/home/tony/prosemirror/bin/pm.js:40:9)
    at Object.<anonymous> (/home/tony/prosemirror/bin/pm.js:361:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)

```

**Comment by adrianheine** [comment]
Seems like you're trying to set up the development environment. Please have a look at the [documentation](http://prosemirror.net/docs/) for how to use ProseMirror in your projects.
